/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.example.project;

public class App {
    public static void main(String[] args) {
        System.out.println("Hello world");
    }
}
